apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "autonomous-enterprise.fullname" . }}-web
  labels: {{- include "autonomous-enterprise.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.web.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
