{{- if .Values.role.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "autonomous-enterprise.fullname" . }}-infra-agent
  labels: {{- include "autonomous-enterprise.labels" . | nindent 4 }}
rules:
  - apiGroups: [apps]
    resources: [deployments]
    resourceNames: []
    verbs: [get, list, watch]
  - apiGroups: [apps]
    resources: [deployments/scale]
    verbs: [get, update, patch]
{{- end }}
