{{- if and (eq .Values.secretManagement.mode "sealedSecret") .Values.secretManagement.sealedSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "autonomous-enterprise.fullname" . }}-secrets
  labels: {{- include "autonomous-enterprise.labels" . | nindent 4 }}
spec:
  encryptedData: {{- toYaml .Values.secretManagement.sealedSecret.encryptedData | nindent 4 }}
  template: {metadata: {name: {{ include "autonomous-enterprise.fullname" . }}-secrets}}
{{- else if and (eq .Values.secretManagement.mode "externalSecret") .Values.secretManagement.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "autonomous-enterprise.fullname" . }}-secrets
spec:
  refreshInterval: {{ .Values.secretManagement.externalSecret.refreshInterval }}
  secretStoreRef: {{- toYaml .Values.secretManagement.externalSecret.secretStoreRef | nindent 4 }}
  target: {name: {{ include "autonomous-enterprise.fullname" . }}-secrets}
  dataFrom: [{extract: {key: {{ .Values.secretManagement.externalSecret.remoteKey }}}}]
{{- end }}
