{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "autonomous-enterprise.serviceAccountName" . }}
  labels: {{- include "autonomous-enterprise.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
